import { CarModel, Feature, SiteContent } from '@/types/database';

export const carModels: CarModel[] = [
  {
    id: '1',
    name: 'ET7',
    category: 'ET',
    tagline: 'The flagship sedan that redefines luxury electric driving',
    range_km: 610,
    top_speed_kmh: 200,
    acceleration_0_100: 3.8,
    battery_kwh: 100,
    hero_image_url: '/images/hero-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 69900,
    is_featured: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'ET5',
    category: 'ET',
    tagline: 'Sporty elegance meets sustainable performance',
    range_km: 550,
    top_speed_kmh: 195,
    acceleration_0_100: 4.3,
    battery_kwh: 75,
    hero_image_url: '/images/hero-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 52900,
    is_featured: false,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'EC7',
    category: 'EC',
    tagline: 'The electric coupe SUV with breathtaking performance',
    range_km: 490,
    top_speed_kmh: 200,
    acceleration_0_100: 3.8,
    battery_kwh: 100,
    hero_image_url: '/images/hero-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 74900,
    is_featured: false,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'EC6',
    category: 'EC',
    tagline: 'A coupe SUV that blends style with intelligence',
    range_km: 465,
    top_speed_kmh: 195,
    acceleration_0_100: 4.5,
    battery_kwh: 75,
    hero_image_url: '/images/hero-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 62900,
    is_featured: false,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'ES8',
    category: 'ES',
    tagline: 'The premium smart electric flagship SUV',
    range_km: 510,
    top_speed_kmh: 200,
    acceleration_0_100: 4.1,
    battery_kwh: 100,
    hero_image_url: '/images/hero-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 79900,
    is_featured: false,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'ES6',
    category: 'ES',
    tagline: 'Smart electric SUV built for everyday excellence',
    range_km: 480,
    top_speed_kmh: 195,
    acceleration_0_100: 4.5,
    battery_kwh: 75,
    hero_image_url: '/images/community-car.jpg',
    side_image_url: '/images/car-side.jpg',
    price_usd: 55900,
    is_featured: false,
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const features: Feature[] = [
  {
    id: '1',
    number: '01',
    title: 'Cutting-Edge Technology',
    description: 'Experience The Future Of Navigation With Our Advanced ADAS System, Featuring 33 High-Performance Sensors, LiDAR Technology & Ultra Long Range Capabilities With 8MP High-Resolution Cameras.',
    icon_url: '',
    display_order: 1,
  },
  {
    id: '2',
    number: '02',
    title: 'Nymi Voice Assistant',
    description: 'Meet Nymi, Your Personal Digital Auto Assistant That Understands Natural Language, Controls Your Vehicle\'s Functions, And Even Anticipates Your Needs Through AI-Powered Learning.',
    icon_url: '',
    display_order: 2,
  },
  {
    id: '3',
    number: '03',
    title: 'Sustainable Innovation',
    description: 'NIO Is Committed To Creating A Greener Future Through Innovative Battery Swapping, Renewable Energy And AI Recycling Programs, Setting New Standards In Sustainable Luxury.',
    icon_url: '',
    display_order: 3,
  },
  {
    id: '4',
    number: '04',
    title: 'Ownership Experience',
    description: 'NIO Redefines Than A Car - It\'s A Lifestyle. Experience Charging Network, NIO Houses, NIO Life Merchandise, Exclusive Events, And A Community That Shares Your Vision.',
    icon_url: '',
    display_order: 4,
  },
];

export const siteContent: Record<string, SiteContent> = {
  hero: {
    id: '1',
    section_key: 'hero',
    title: 'DRIVE THE FUTURE TODAY',
    subtitle: 'More Than A Car, It\'s A Statement Of Progressive Luxury. Experience The Perfect Blend Of Innovation And Sustainable Elegance.',
    body: '',
    image_url: '/images/hero-car.jpg',
    updated_at: new Date().toISOString(),
  },
  future: {
    id: '2',
    section_key: 'future',
    title: 'The Future of Luxury is Electric',
    subtitle: 'Step into the future of automotive excellence. Advanced technology that transforms every journey into an extraordinary experience.',
    body: '',
    image_url: '',
    updated_at: new Date().toISOString(),
  },
  tech: {
    id: '3',
    section_key: 'tech',
    title: 'Your NIO Adapts And Evolves, Advanced AI Learns Your Preferences While Autonomous Driving Capabilities',
    subtitle: 'And Smart Cockpit Features Create A Seamless Connection Between You And Your Vehicle.',
    body: '',
    image_url: '/images/dashboard.jpg',
    updated_at: new Date().toISOString(),
  },
  beyond: {
    id: '4',
    section_key: 'beyond',
    title: 'Beyond Electric \u2014 Driving The Future Forward',
    subtitle: 'NIO Redefines Cars With Advanced Technology, Comprehensive Design, Smart Services And Sustainable Innovation.',
    body: '',
    image_url: '',
    updated_at: new Date().toISOString(),
  },
  community: {
    id: '5',
    section_key: 'community',
    title: 'Be Part of the Nio Community',
    subtitle: 'Join a vibrant community of forward-thinking drivers who share a passion for innovation, sustainability, and the future of mobility.',
    body: '',
    image_url: '/images/community-car.jpg',
    updated_at: new Date().toISOString(),
  },
};
